modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = "${mod_description}"

[[mixins]]
config = "${mod_id}_base.mixins.json"

#[[mixins]]
#config = "${mod_id}_extra.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${mc_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "prettypipes"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
